Add tests to controllers
principles31/Blog_app pull request #5
Opened 2022-08-29 22:11 UTC by principles31

2022-08-29 22:27 UTC, Munsa1 requested changes
Hi @principles31, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark: Passing Linters
:heavy_check_mark: Correct Gitflow
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-29 22:27 UTC, Munsa1 commented on spec/requests/posts_spec.rb
> +require 'rails_helper'
- [ ] In `posts_spec.rb`, there are 4 tests which are failing. kindly fix this issue
![image](https://user-images.githubusercontent.com/81932478/187309811-08db1cbb-19dc-4306-8449-b35ae0aa47c9.png)

2022-08-30 07:14 UTC, principles31 commented
- [x] In posts_spec.rb, there are 4 tests which are failing. kindly fix this issue
- [x] The requested changes above have been implemented.

2022-08-30 07:15 UTC, principles31 commented
@Munsa1 Thank you

2022-08-30 07:50 UTC, descholar-ceo approved these changes
Hi @principles31 🤝 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
👍🏽 Addressed the requested changes ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-30 07:53 UTC, principles31 commented
@descholar-ceo Thank you for acknowledging this PR.

2022-08-30 07:53 UTC, merged